import React from "react";
import { addDecorator } from "@storybook/react";
import { withTests } from "@storybook/addon-jest";
import { Provider, createStore } from "@frontity/connect";

// The following file is generated by running `npm run test:generate-output`.
// Make sure to run it before running or building storybook!
import results from "../.jest-test-results.json";

// Enable Jest integration for all stories
addDecorator(withTests({ results }));

// We need to expose a store in order for frontity components to work:
// Mock store technique taken from frontity test suite: https://github.com/frontity/frontity/blob/83c5eadb4dffc6275fe4d93b8d379c21449a2727/packages/connect/src/__tests__/connect.tests.jsx#L11
const store = createStore({
  state: {
    // Sensible state value taken from https://github.com/frontity/frontity/blob/83c5eadb4dffc6275fe4d93b8d379c21449a2727/packages/components/__tests__/image.jsdom.tests.tsx#L57
    frontity: {
      rendering: "ssr"
    }
  }
});
addDecorator(storyFn => <Provider value={store}>{storyFn()}</Provider>);
